config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "splash_screen#index"
  resources :categories do
    resources :entities
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: { message: 'Name can not be blank' }
  validates :icon, presence: { message: 'Icon can not be blank' }

  belongs_to :user
  has_and_belongs_to_many :entities
end

app/models/category_entity.rb
class CategoryEntity < ApplicationRecord
  belongs_to :category
  belongs_to :entity
end

app/models/category_entity_join_tabel.rb
class CategoryEntityJoinTabel < ApplicationRecord
end

app/models/entity.rb
class Entity < ApplicationRecord
  validates :name, presence: { message: 'Name can not be empty' }
  validates :amount,
            numericality: { only_float: true, greater_than_or_equal_to: 0,
                            message: 'Amount should be greater or equal to 0' }
  belongs_to :user
  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum: 3 }
  validates :email, :password, presence: true, length: { minimum: 3 }
  has_many :entities
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_out_path_for(_user)
    new_user_session_path
  end

  def after_sign_in_path_for(_user)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def show; end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon, :user_id)
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entity, only: %i[show edit update destroy]

  def index
    @category = Category.find(params[:category_id])
    @category_entities = CategoryEntity.where(category_id: @category.id)
    @entity_ids = []
    @category_entities.each { |category_entity| @entity_ids.push(category_entity.entity_id) }
    @entities = Entity.where(id: @entity_ids).order(created_at: :desc)
    @total = 0
    @category_entities.each { |category_entity| @total += category_entity.entity.amount }
  end

  def show; end

  def new
    @entity = Entity.new
  end

  def edit; end

  def create
    @entity = Entity.new(entity_params)
    @category = Category.find(params[:category_id])

    respond_to do |format|
      if @entity.save
        CategoryEntity.create!(category_id: params[:category_id], entity_id: @entity.id)
        flash[:success] = 'Transaction created successfully.'
        format.html { redirect_to category_entities_url(@entity), notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_entity
    @entity = Entity.find(params[:id])
  end

  def entity_params
    params.require(:entity).permit(:name, :amount, :user_id)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def new; end

  def create; end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entites_helper.rb
module EntitesHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/splah_screen_helper.rb
module SplahScreenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div class="cards">
  <div class="card card-1">
    <div class="card__icon"><i class="fas fa-bolt"></i></div>
    <p class="card__exit"><i class="fas fa-times"></i></p>
    <h2 class="card__title"><%= category.name %></h2>
    <p class="card__apply">
      <a class="card__link" href="#"><%= category.icon %><i class="fas fa-arrow-right"></i></a>
    </p>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>
  <div>
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Categories</h1>
<div id="categories">
  <% @categories.each do |category| %>
    <%= link_to category_entities_url(category) do %>
      <%= render category %>
    <% end %>
  <% end %>
</div>
<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>
<%= render "form", category: @category %>
<br>
<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to category_entities_url(@category) do %>
  <%= render @category %>
<% end %>
<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/entities/_entity.html.erb
<div class="cards">
  <div class="card card-1">
    <div class="card__icon"><i class="fas fa-bolt"></i></div>
    <p class="card__exit"><i class="fas fa-times"></i></p>
    <h2 class="card__title"><%= entity.name %></h2>
    <p class="card__apply">
      <a class="card__link" href="#"><%= entity.amount %><i class="fas fa-arrow-right"></i></a>
    </p>
  </div>
</div>

app/views/entities/_form.html.erb
<%= form_with(model: @entity, url: category_entities_path, method: :post, local: true) do |form| %>
  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>
      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>
  <div>
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entities/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="heading">
  <h1 class="heading__title">Transactions</h1>
</div>
  <h2>Total price <%= @total %></h2>
<%= link_to "New entity", new_category_entity_path, :class => "fcc-btn" %>
<div id="entities">
  <% @entities.each do |entity| %>
      <%= render entity %>
  <% end %>
  <%= link_to 'Retutn Categories',  categories_path %>
</div>

app/views/entities/new.html.erb
<h1>New entity</h1>
<%= render "form", entity: @entity %>
<br>
<div>
  <%= link_to "Back to entities", category_entities_path %>
</div>

app/views/entities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entity %>

<div>
  <%= link_to "Edit this entity", edit_entity_path(@entity) %> |
  <%= link_to "Back to entities", entities_path %>
  <%= button_to "Destroy this entity", @entity, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/splash_screen/index.html.erb
<section>
  <div class="splash_container">
    <h1 class="splash_title">Rails Budget App</h1>
    <div class="splash_button_container">
      <%= button_to "LOG IN", new_user_session_path, class: "log_in_button", method: :get%>
      <%= link_to 'Register',  new_user_registration_path, class: "sign_up_link" %>
    </div>
  </div>
</section>